// old-webapp/src/components/ui/CompletionCircle.tsx
import "./CompletionCircle.css";

interface CompletionCircleProps {
  filled?: boolean;
  size?: "sm" | "md" | "lg";
  disabled?: boolean;
  onClick?: () => void;
  className?: string;
}

/**
 * The signature completion circle — empty border → filled teal + check.
 * sm = 20px (lists), md = 32px (hero cards), lg = 44px (empty states).
 */
export function CompletionCircle({
  filled = false,
  size = "sm",
  disabled = false,
  onClick,
  className = "",
}: CompletionCircleProps) {
  return (
    <button
      type="button"
      className={[
        "aa-cc",
        `aa-cc--${size}`,
        filled ? "aa-cc--filled" : "",
        disabled ? "aa-cc--disabled" : "",
        className,
      ].filter(Boolean).join(" ")}
      onClick={disabled ? undefined : onClick}
      disabled={disabled}
      aria-label={filled ? "Completed" : "Mark complete"}
      aria-pressed={filled}
    >
      <svg className="aa-cc__check" viewBox="0 0 16 16" fill="none">
        <path
          d="M3.5 8.5l3 3 6-7"
          stroke="currentColor"
          strokeWidth="2.4"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    </button>
  );
}

// apps/web/src/lib/components/CompletionCircle.svelte
<script lang="ts">
  // CompletionCircle — the quiet done ring (empty-state icon, Today's mark).
  let { size = 40 }: { size?: number } = $props();
  const r = 45;
  const circumference = 2 * Math.PI * r;
</script>

<svg
  width={size}
  height={size}
  viewBox="0 0 100 100"
  role="img"
  aria-label="Completed"
  class="aa-completion-circle"
>
  <circle cx="50" cy="50" {r} fill="none" stroke="var(--aa-border, oklch(0.9 0.005 240))" stroke-width="6" />
  <circle
    cx="50"
    cy="50"
    {r}
    fill="none"
    stroke="var(--aa-teal)"
    stroke-width="6"
    stroke-linecap="round"
    stroke-dasharray={circumference}
    stroke-dashoffset={circumference * 0.25}
    transform="rotate(-90 50 50)"
  />
</svg>

<style>
  .aa-completion-circle {
    display: block;
  }
</style>
