// web/src/lib/components/ui/PickerSheet.svelte
<script lang="ts">
  // PickerSheet — shared bottom-sheet list for choosing one Project, Goal,
  // or similar destination (webapp ui/PickerSheet port). Classes + Picker-
  // Sheet.css verbatim; the sheet shell is the shared BottomSheet.
  import BottomSheet from "./BottomSheet.svelte";
  import "./PickerSheet.css";

  interface PickerItem {
    id: string;
    label: string;
    meta?: string | null;
    current?: boolean;
  }

  let {
    title,
    items,
    emptyMessage,
    onPick,
    onClose,
  }: {
    title: string;
    items: PickerItem[];
    emptyMessage?: string;
    onPick: (id: string) => void;
    onClose: () => void;
  } = $props();
</script>

<BottomSheet {title} {onClose}>
  {#if items.length === 0 && emptyMessage}
    <p class="aa-picker-sheet__empty">{emptyMessage}</p>
  {:else}
    <ul class="aa-picker-sheet__list">
      {#each items as item (item.id)}
        <li>
          <button
            type="button"
            class="aa-picker-sheet__item {item.current ? "current" : ""}"
            onclick={() => onPick(item.id)}
          >
            <span class="aa-picker-sheet__name">{item.label}</span>
            {#if item.meta}<span class="aa-picker-sheet__meta">{item.meta}</span>{/if}
            <span class="aa-picker-sheet__num">{items.indexOf(item) + 1}</span>
          </button>
        </li>
      {/each}
    </ul>
  {/if}
</BottomSheet>

// webapp/src/components/ui/PickerSheet.tsx
import { BottomSheet } from "./BottomSheet";
import "./PickerSheet.css";

export interface PickerSheetItem {
  id: string;
  label: string;
  meta?: string | null;
  current?: boolean;
}

export interface PickerSheetAction {
  label: string;
  onPick: () => void;
}

interface PickerSheetProps {
  title: string;
  items: PickerSheetItem[];
  emptyMessage?: string;
  action?: PickerSheetAction;
  onPick: (id: string) => void;
  onClose: () => void;
}

/**
 * PickerSheet — shared bottom-sheet list for choosing one Project, Goal, or
 * similar destination. Keeps the sheet rhythm consistent across flows.
 */
export function PickerSheet({
  title,
  items,
  emptyMessage,
  action,
  onPick,
  onClose,
}: PickerSheetProps) {
  return (
    <BottomSheet title={title} onClose={onClose}>
      {items.length === 0 && emptyMessage ? (
        <p className="aa-picker-sheet__empty">{emptyMessage}</p>
      ) : (
        <ul className="aa-picker-sheet__list">
          {items.map((item, index) => (
            <li key={item.id}>
              <button
                type="button"
                className={`aa-picker-sheet__item ${item.current ? "current" : ""}`}
                onClick={() => onPick(item.id)}
              >
                <span className="aa-picker-sheet__name">{item.label}</span>
                {item.meta && <span className="aa-picker-sheet__meta">{item.meta}</span>}
                <span className="aa-picker-sheet__num">{index + 1}</span>
              </button>
            </li>
          ))}
          {action && (
            <li>
              <button
                type="button"
                className="aa-picker-sheet__item aa-picker-sheet__item--action"
                onClick={action.onPick}
              >
                <span className="aa-picker-sheet__name">{action.label}</span>
              </button>
            </li>
          )}
        </ul>
      )}
    </BottomSheet>
  );
}
