// web/src/lib/components/SnoozeSheet.svelte
<script lang="ts">
  // SnoozeSheet — the "Not now" flow: 5 presets; the parent runs the
  // mutation and closes (webapp ui/SnoozeSheet port).
  import BottomSheet from "./BottomSheet.svelte";
  import Chip from "./Chip.svelte";
  import type { SnoozePreset } from "../dto";

  const PRESETS: { preset: SnoozePreset; label: string; hint: string }[] = [
    { preset: "1h", label: "In 1 hour", hint: "quick breather" },
    { preset: "3h", label: "In 3 hours", hint: "later today" },
    { preset: "tomorrow", label: "Tomorrow", hint: "9am tomorrow" },
    { preset: "weekend", label: "This weekend", hint: "Saturday" },
    { preset: "someday", label: "Someday", hint: "no date, stop nagging" },
  ];

  let {
    taskTitle,
    onSnooze,
    onClose,
  }: {
    taskTitle: string;
    onSnooze: (preset: SnoozePreset) => Promise<void> | void;
    onClose: () => void;
  } = $props();

  let busy = $state<SnoozePreset | null>(null);

  async function handle(preset: SnoozePreset) {
    if (busy) return;
    busy = preset;
    try {
      await onSnooze(preset);
      onClose();
    } catch {
      busy = null;
    }
  }
</script>

<BottomSheet title="Not now" {onClose}>
  <p class="aa-snooze__task">
    <Chip variant="default" small>{taskTitle}</Chip>
  </p>
  <ul class="aa-snooze__list">
    {#each PRESETS as p (p.preset)}
      <li>
        <button
          type="button"
          class="aa-snooze__option"
          disabled={busy !== null}
          onclick={() => handle(p.preset)}
        >
          <span class="aa-snooze__option-label">{p.label}</span>
          <span class="aa-snooze__option-hint">{p.hint}</span>
        </button>
      </li>
    {/each}
  </ul>
</BottomSheet>

<style>
  .aa-snooze__task {
    margin: 0 0 0.75rem;
  }
  .aa-snooze__list {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
  }
  .aa-snooze__option {
    display: flex;
    align-items: baseline;
    justify-content: space-between;
    gap: 1rem;
    width: 100%;
    background: none;
    border: none;
    padding: 0.7rem 0.35rem;
    font-size: var(--aa-text-md);
    color: var(--aa-text);
    cursor: pointer;
    border-radius: 8px;
  }
  .aa-snooze__option:hover:not(:disabled) {
    background: var(--aa-surface-muted, oklch(0.97 0.004 240));
  }
  .aa-snooze__option:disabled {
    opacity: 0.55;
  }
  .aa-snooze__option-label {
    font-weight: var(--aa-weight-medium);
  }
  .aa-snooze__option-hint {
    font-size: var(--aa-text-sm);
    color: var(--aa-text-muted, oklch(0.5 0.01 240));
  }
</style>

// webapp/src/components/ui/SnoozeSheet.tsx
import { useState } from "react";
import { BottomSheet, Chip } from "./index";
import "./Overlays.css";

export type SnoozePreset = "1h" | "3h" | "tomorrow" | "weekend" | "someday";

const PRESETS: { preset: SnoozePreset; label: string; hint: string }[] = [
  { preset: "1h", label: "In 1 hour", hint: "quick breather" },
  { preset: "3h", label: "In 3 hours", hint: "later today" },
  { preset: "tomorrow", label: "Tomorrow", hint: "9am tomorrow" },
  { preset: "weekend", label: "This weekend", hint: "Saturday" },
  { preset: "someday", label: "Someday", hint: "no date, stop nagging" },
];

/**
 * SnoozeSheet — the "Not now" flow from the Next card.
 *
 * A BottomSheet of 5 snooze presets. Calls onSnooze with the chosen preset; the
 * parent runs the mutation (snoozeTask) and closes the sheet. The task leaves
 * the focus queue until the snooze expires.
 *
 * FEATURES.md F11 + modal-approach.md §03.
 */
export function SnoozeSheet({
  taskTitle,
  onSnooze,
  onClose,
}: {
  taskTitle: string;
  onSnooze: (preset: SnoozePreset) => Promise<void> | void;
  onClose: () => void;
}) {
  const [busy, setBusy] = useState<SnoozePreset | null>(null);

  const handle = async (preset: SnoozePreset) => {
    if (busy) return;
    setBusy(preset);
    try {
      await onSnooze(preset);
      onClose();
    } catch {
      setBusy(null);
    }
  };

  return (
    <BottomSheet title="Not now" onClose={onClose}>
      <p className="aa-snooze__task">
        <Chip variant="default" small>{taskTitle}</Chip>
      </p>
      <ul className="aa-snooze__list">
        {PRESETS.map((p) => (
          <li key={p.preset}>
            <button
              type="button"
              className="aa-snooze__option"
              disabled={busy !== null}
              onClick={() => handle(p.preset)}
            >
              <span className="aa-snooze__option-label">{p.label}</span>
              <span className="aa-snooze__option-hint">{p.hint}</span>
            </button>
          </li>
        ))}
      </ul>
    </BottomSheet>
  );
}
