// webapp/src/app/FeedbackDialog.tsx
import { useEffect, useRef, useState } from "react";
import { Button, Kbd, submitOnModEnter } from "../components/ui";
import "../components/ui/Overlays.css";

type FeedbackDialogProps = {
  onSubmit: (message: string) => Promise<void>;
  onClose: () => void;
};

export function FeedbackDialog({ onSubmit, onClose }: FeedbackDialogProps) {
  const [message, setMessage] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);

  useEffect(() => {
    textareaRef.current?.focus();
  }, []);

  const canSubmit = message.trim().length > 0 && !submitting;

  async function submit() {
    if (!canSubmit) return;
    setSubmitting(true);
    setError(null);
    try {
      await onSubmit(message.trim());
      onClose();
    } catch {
      setError("Could not send feedback. Try again.");
      setSubmitting(false);
    }
  }

  return (
    <div
      className="aa-overlay"
      role="dialog"
      aria-modal="true"
      aria-label="Leave feedback"
      onClick={onClose}
    >
      <div
        className="aa-overlay-card aa-overlay-card--sm aa-feedback"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="aa-feedback__head">
          <div>
            <h2 className="aa-feedback__title">Leave feedback</h2>
            <p className="aa-feedback__sub">Tell us what happened, what felt off, or what would help.</p>
          </div>
          <button
            type="button"
            className="aa-overlay__close"
            onClick={onClose}
            aria-label="Close"
          >
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
              <path d="M4 4l8 8M12 4l-8 8" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" />
            </svg>
          </button>
        </div>

        <textarea
          ref={textareaRef}
          className="aa-feedback__textarea"
          rows={5}
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          onKeyDown={(e) => {
            // ⌘/Ctrl+Enter submits; plain Enter inserts a newline (multi-line box).
            submitOnModEnter(e, () => void submit());
          }}
          placeholder="What should we know?"
          maxLength={4000}
          disabled={submitting}
        />

        {error && <p className="aa-feedback__error">{error}</p>}

        <div className="aa-feedback__foot">
          <span className="aa-feedback__count">{message.length}/4000</span>
          <div className="aa-feedback__actions">
            <Kbd>⌘↵</Kbd>
            <Button variant="secondary" size="sm" onClick={onClose} disabled={submitting}>
              Cancel
            </Button>
            <Button size="sm" onClick={submit} disabled={!canSubmit}>
              {submitting ? "Sending" : "Send"}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

// web/src/lib/components/FeedbackDialog.svelte
<script lang="ts">
  /**
   * FeedbackDialog — the "Leave feedback" overlay, ported 1:1 from
   * webapp/src/app/FeedbackDialog.tsx (the .aa-feedback styles ship from
   * ui/Overlays.css, which this component owns the import for).
   *
   *   Enter        → newline (multi-line box)
   *   ⌘/Ctrl+Enter → submit
   *   Esc          → close
   *
   * Submit failures keep the dialog open with an error line — never lose a
   * half-written report.
   */
  import "../components/ui/Overlays.css";
  import "../components/ui/Button.css";
  import { feedback } from "../stores/feedback.svelte";

  const MAX_LENGTH = 4000;

  let message = $state("");
  let error = $state<string | null>(null);
  let taEl: HTMLTextAreaElement | null = $state(null);

  const canSubmit = $derived(message.trim().length > 0 && !feedback.submitting);

  // Autofocus on open (webapp's mount effect).
  $effect(() => {
    taEl?.focus();
  });

  function close() {
    feedback.hide();
  }

  async function submit() {
    if (!canSubmit) return;
    error = null;
    try {
      await feedback.submit(message.trim());
      close();
    } catch {
      error = "Could not send feedback. Try again.";
    }
  }

  function onTextareaKeydown(event: KeyboardEvent) {
    // ⌘/Ctrl+Enter submits; plain Enter inserts a newline (multi-line box).
    if (event.key === "Enter" && (event.metaKey || event.ctrlKey)) {
      event.preventDefault();
      void submit();
    }
  }

  function onWindowKeydown(event: KeyboardEvent) {
    if (event.key === "Escape") close();
  }
</script>

<svelte:window onkeydown={onWindowKeydown} />

<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_noninteractive_element_interactions -->
<div
  class="aa-overlay"
  role="dialog"
  tabindex="-1"
  aria-modal="true"
  aria-label="Leave feedback"
  onclick={close}
>
  <!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
  <div class="aa-overlay-card aa-overlay-card--sm aa-feedback" onclick={(e) => e.stopPropagation()}>
    <div class="aa-feedback__head">
      <div>
        <h2 class="aa-feedback__title">Leave feedback</h2>
        <p class="aa-feedback__sub">Tell us what happened, what felt off, or what would help.</p>
      </div>
      <button type="button" class="aa-overlay__close" aria-label="Close" onclick={close}>×</button>
    </div>

    <textarea
      bind:this={taEl}
      class="aa-feedback__textarea"
      rows="5"
      bind:value={message}
      onkeydown={onTextareaKeydown}
      placeholder="What should we know?"
      maxlength={MAX_LENGTH}
      disabled={feedback.submitting}
    ></textarea>

    {#if error}
      <p class="aa-feedback__error" role="alert">{error}</p>
    {/if}

    <div class="aa-feedback__foot">
      <span class="aa-feedback__count">{message.length}/{MAX_LENGTH}</span>
      <div class="aa-feedback__actions">
        <kbd class="aa-kbd">⌘↵</kbd>
        <button
          type="button"
          class="aa-btn aa-btn--secondary aa-btn--sm"
          onclick={close}
          disabled={feedback.submitting}
        >
          Cancel
        </button>
        <button
          type="button"
          class="aa-btn aa-btn--primary aa-btn--sm"
          onclick={() => void submit()}
          disabled={!canSubmit}
        >
          {feedback.submitting ? "Sending" : "Send"}
        </button>
      </div>
    </div>
  </div>
</div>
