// webapp/src/components/ui/TriageCard.tsx
import type { ReactNode } from "react";
import { Chip } from "./Chip";
import { Linkify } from "./Linkify";
import { AttachmentGallery, type AttachmentThumb } from "./AttachmentThumbs";
import "./TriageCard.css";

export type TriageChipTone = "date" | "priority" | "tag";

export interface TriageChip {
  tone: TriageChipTone;
  label: string;
}

export type TriageExit = "right" | "left" | "up" | "down" | null;

interface TriageCardProps {
  /** The captured item text */
  body: string;
  /** When provided, the captured text becomes an always-visible title editor. */
  onBodyChange?: (body: string) => void;
  /** Exit the body editor on blur — the card returns to its reading view. */
  onBodyBlur?: () => void;
  /** Show the edit affordance on the read-only body (Classify step) — the
   *  body stays a linkified reading surface until the user asks to edit. */
  onBodyEdit?: () => void;
  /** Focus the editor on mount (used when an explicit edit toggle opened it). */
  autoFocusBody?: boolean;
  /** Editor label — "Title" when the edit names the future entity (Spec
   *  step), "Captured text" when it edits the stored InboxItem (Classify). */
  bodyLabel?: string;
  /** Meta line (e.g. "captured 14 min ago") */
  meta?: string;
  /** Parsed-token chips */
  chips?: TriageChip[];
  /** Captured images — shown large while the item is being decided so it
      can be judged by what was shared, not just its text. Multiple images
      carousel; click opens the full-size lightbox. */
  media?: AttachmentThumb[];
  /** Exit animation direction; null = at rest */
  exit?: TriageExit;
  /** Brief confirm pulse when dispatched */
  dispatched?: boolean;
  /** Prep state (next card entering) */
  entering?: boolean;
  children?: ReactNode;
}

const CHIP_VARIANT: Record<TriageChipTone, "teal" | "amber" | "violet"> = {
  date: "teal",
  priority: "amber",
  tag: "violet",
};

/**
 * TriageCard — a single captured item during the Tinder-style triage walkthrough.
 *
 * Shows the item text, "captured X ago" meta, and parsed-token chips.
 * Exit direction encodes the dispatch decision (right/left/up/down).
 * From triage-tinder.html `.card`.
 */
export function TriageCard({
  body,
  onBodyChange,
  onBodyBlur,
  onBodyEdit,
  autoFocusBody = false,
  bodyLabel = "Title",
  meta,
  chips,
  media,
  exit = null,
  dispatched = false,
  entering = false,
  children,
}: TriageCardProps) {
  const cls = [
    "aa-triage-card",
    exit ? `aa-triage-card--exit-${exit}` : "",
    dispatched ? "aa-triage-card--dispatched" : "",
    entering ? "aa-triage-card--entering" : "",
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <div className={cls}>
      {onBodyChange ? (
        <label className="aa-triage-card__title-field">
          <span className="aa-triage-card__title-label">{bodyLabel}</span>
          <textarea
            className="aa-triage-card__title-input"
            aria-label={bodyLabel}
            value={body}
            onChange={(event) => onBodyChange(event.target.value)}
            onBlur={onBodyBlur}
            autoFocus={autoFocusBody}
            rows={1}
            placeholder="What needs doing?"
          />
        </label>
      ) : (
        <div className="aa-triage-card__body-wrap">
          <p
            className={`aa-triage-card__body${onBodyEdit ? " aa-triage-card__body--editable" : ""}`}
            onClick={
              onBodyEdit
                ? (event) => {
                    // Click-the-text-to-edit (the simple-list rename pattern).
                    // A click on a linkified URL is the link's own — open it,
                    // don't turn the body into an editor.
                    if ((event.target as HTMLElement).closest("a")) return;
                    onBodyEdit();
                  }
                : undefined
            }
          >
            <Linkify text={body} />
          </p>
          {onBodyEdit && (
            <button
              type="button"
              className="aa-triage-card__body-edit"
              onClick={onBodyEdit}
              aria-label={`Edit ${bodyLabel.toLowerCase()}`}
              title={`Edit ${bodyLabel.toLowerCase()}`}
            >
              <svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
                <path
                  d="M11.3 2.6l2.1 2.1L6 12.1l-2.8.7.7-2.8L11.3 2.6z"
                  stroke="currentColor"
                  strokeWidth="1.5"
                  strokeLinejoin="round"
                  strokeLinecap="round"
                />
              </svg>
            </button>
          )}
        </div>
      )}
      {meta && <p className="aa-triage-card__meta">{meta}</p>}
      {chips && chips.length > 0 && (
        <div className="aa-triage-card__chips">
          {chips.map((c, i) => (
            <Chip key={i} variant={CHIP_VARIANT[c.tone]}>
              {c.label}
            </Chip>
          ))}
        </div>
      )}
      {media && media.length > 0 && (
        <div className="aa-triage-card__media">
          <AttachmentGallery attachments={media} />
        </div>
      )}
      {children}
    </div>
  );
}

// web/src/lib/components/TriageCard.svelte
<script lang="ts">
  /**
   * TriageCard — a single captured item during the review walkthrough
   * (ported from webapp/src/components/ui/TriageCard.tsx; styles from
   * styles/TriageCard.css). The body is a reading surface (URLs linkified)
   * until clicked / the pencil toggles its editor. Exit direction encodes
   * the dispatch decision. Captured images (S12) render as the
   * AttachmentGallery between the body and the meta line — the item is
   * judged by what was actually shared.
   */
  import type { Snippet } from "svelte";
  import AttachmentGallery from "./ui/AttachmentGallery.svelte";
  import Chip from "./ui/Chip.svelte";
  import Linkify from "./ui/Linkify.svelte";
  import type { TriageChip, TriageExit } from "../triage/flow";

  let {
    body,
    onBodyChange,
    onBodyBlur,
    onBodyEdit,
    autoFocusBody = false,
    bodyLabel = "Title",
    meta,
    chips,
    attachments = [],
    exit = null,
    dispatched = false,
    entering = false,
    children,
  }: {
    body: string;
    onBodyChange?: (body: string) => void;
    onBodyBlur?: () => void;
    onBodyEdit?: () => void;
    autoFocusBody?: boolean;
    bodyLabel?: string;
    meta?: string;
    chips?: TriageChip[];
    /** Captured-image metadata (S12) — the gallery renders above the meta. */
    attachments?: { id: string; filename: string }[];
    exit?: TriageExit;
    dispatched?: boolean;
    entering?: boolean;
    children: Snippet;
  } = $props();

  const CHIP_VARIANT: Record<TriageChip["tone"], "teal" | "amber" | "violet"> = {
    date: "teal",
    priority: "amber",
    tag: "violet",
  };

  let titleEl: HTMLTextAreaElement | null = $state(null);

  $effect(() => {
    if (autoFocusBody && titleEl) {
      titleEl.focus();
      titleEl.selectionStart = titleEl.value.length;
    }
  });

  function onBodyClick(e: MouseEvent): void {
    if (!onBodyEdit) return;
    // A click on a linkified URL is the link's own — open it, don't turn
    // the body into an editor.
    if ((e.target as HTMLElement).closest("a")) return;
    onBodyEdit();
  }
</script>

<div
  class="aa-triage-card {exit ? `aa-triage-card--exit-${exit}` : ''}
    {dispatched ? "aa-triage-card--dispatched" : ""}
    {entering ? "aa-triage-card--entering" : ""}"
>
  {#if onBodyChange}
    <label class="aa-triage-card__title-field">
      <span class="aa-triage-card__title-label">{bodyLabel}</span>
      <textarea
        bind:this={titleEl}
        class="aa-triage-card__title-input"
        aria-label={bodyLabel}
        value={body}
        oninput={(e) => onBodyChange?.(e.currentTarget.value)}
        onblur={() => onBodyBlur?.()}
        rows={1}
        placeholder="What needs doing?"
      ></textarea>
    </label>
  {:else}
    <div class="aa-triage-card__body-wrap">
      <!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions, a11y_no_noninteractive_element_interactions -->
      <p
        class="aa-triage-card__body {onBodyEdit ? "aa-triage-card__body--editable" : ""}"
        onclick={onBodyClick}
      >
        <Linkify text={body} />
      </p>
      {#if onBodyEdit}
        <button
          type="button"
          class="aa-triage-card__body-edit"
          onclick={onBodyEdit}
          aria-label="Edit {bodyLabel.toLowerCase()}"
          title="Edit {bodyLabel.toLowerCase()}"
        >
          <svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
            <path
              d="M11.3 2.6l2.1 2.1L6 12.1l-2.8.7.7-2.8L11.3 2.6z"
              stroke="currentColor"
              stroke-width="1.5"
              stroke-linejoin="round"
              stroke-linecap="round"
            />
          </svg>
        </button>
      {/if}
    </div>
  {/if}
  {#if attachments.length > 0}
    <div class="aa-triage-card__gallery">
      <AttachmentGallery {attachments} />
    </div>
  {/if}
  {#if meta}
    <p class="aa-triage-card__meta">{meta}</p>
  {/if}
  {#if chips && chips.length > 0}
    <div class="aa-triage-card__chips">
      {#each chips as c, i (i)}
        <Chip variant={CHIP_VARIANT[c.tone]}>{c.label}</Chip>
      {/each}
    </div>
  {/if}
  {@render children()}
</div>
